name: Ketjuta Pokemon-vahti

on:
  workflow_run:
    workflows: ["Pokemon 30th vahti"]
    types: [completed]

jobs:
  watch:
    if: contains(fromJSON('["success","failure","timed_out"]'), github.event.workflow_run.conclusion)
    uses: ./.github/workflows/watch-job.yml
    secrets: inherit
