name: Pokemon 30th vahti

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  workflow_run:
    workflows: ["Ketjuta Pokemon-vahti"]
    types: [completed]

jobs:
  watch:
    if: github.event_name != 'workflow_run' || contains(fromJSON('["success","failure","timed_out"]'), github.event.workflow_run.conclusion)
    uses: ./.github/workflows/watch-job.yml
    secrets: inherit
